# Generated by Django 4.1.2 on 2022-10-30 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slg',
            new_name='slug',
        ),
    ]
